### ISSUE TITLE
This activly working?

### ISSUE THREAD

**Issue by NoelHuibers** [matthiasdotsh/nix-cppyy#1]
Hey,

saw this repo and currently try getting cppyy to work on my nixos system myself.
Is this a working approach?

If you don't mind, we can communicate over noel@huibers.io or any other option :)

**Comment by matthiasdotsh** [comment]
Nice to see someone else who wants to use cppyy under nix

>  Is this a working approach?

Yes, its working, you should be able to clone the repo and execute the steps from README.md

The current version was enough for me to get my work done, but PR to bring it closer to a real nix-package are welcome.

**Comment by NoelHuibers** [comment]
I'm new to NixOS and try using NS-3 which needs cppyy for python bindings.

I use a flake setup instead of nix shell, which makes it not as reproducible, but the test_cppyy.py did work in a nix-shell.

What would be needed to make it a real nix-package?

**Comment by matthiasdotsh** [comment]
I started to create [packages](https://github.com/matthiasdotsh/nix-cppyy/blob/main/overlay.nix) for all cppyy components [cppyy-cling](https://github.com/matthiasdotsh/nix-cppyy/blob/main/cppyy-cling/default.nix), [cppyy-backend](https://github.com/matthiasdotsh/nix-cppyy/blob/main/cppyy-backend/default.nix), [CPyCppyy](https://github.com/matthiasdotsh/nix-cppyy/blob/main/CPyCppyy/default.nix) and [cppyy](https://github.com/matthiasdotsh/nix-cppyy/blob/main/cppyy/default.nix).

However it looks like some `.so` files are in the wrong place.
I worked around this in [this shellHook](https://github.com/matthiasdotsh/nix-cppyy/blob/main/release.nix#L17).

Unfortunately I have no idea why the `.so` files are in the wrong place. I had to hack around in the individual` .nix` files quite a bit to get it running at all, but at the time I made an effort to describe why the hacks were necessary.

I think that it should actually primarily be about getting rid of the [`shellHook`](https://github.com/matthiasdotsh/nix-cppyy/blob/main/release.nix#L17). As soon as that is the case, you should be able to use cppy as a dependency for other packages.

**Comment by NoelHuibers** [comment]
I will take a look into it!
